### ISSUE TITLE
On mobile -- in discover view refreshes map when moved and cuts off descriptions on press.

### ISSUE THREAD

**Issue by JordanFreitas** [plastic-oceans461/plastic-oceans461.github.io#22]
Will submit screenshots later.

**Comment by lisakoss** [comment]
Are you resizing the page when you're moving? Or are you simply dragging the mouse throughout the map when this refresh happens?

But since we're using React and SVG elements with D3 that both use target the DOM, the map has to re-render when the page is resized. So if you resize the page at any time, then the map has to rerender to keep the coordinates at accurate points. 

Although, good catch! The font size should be smaller on smaller resolutions and phones for tooltips. :)

**Comment by lisakoss** [comment]
Tooltips should now have the highest z-index on the page so they won't be hidden behind any other element. :) Also I found that since the map is draggable, you have to use two fingers in order to move it on mobile devices (since our app is not an app that is downloaded directly to your phone). If not done with two fingers, you have the possibly of changing the browser window size slightly, which triggers a refresh as intended.
