### ISSUE TITLE
Not all points on the map display information

### ISSUE THREAD

**Issue by JourneyToTheWes** [plastic-oceans461/plastic-oceans461.github.io#23]
![image](https://user-images.githubusercontent.com/15175754/40897673-3578f1b6-6771-11e8-91ea-18bbaed1e90f.png)
Only the number 13 displays information. The rest of them don't display anything when clicked.

**Comment by JourneyToTheWes** [comment]
Just realized that some work when I zoom out of the map. I have to zoom in and out to get some of the icons to display the information.

**Comment by alexiskoss** [comment]
@JourneyToTheWes Can you tell me what browser (version number too if possible) that you're using?

**Comment by lisakoss** [comment]
This has been fixed! We switched to reactstrap popovers so now this functionality works in all browsers outside of Chrome. :)

We discovered that this issue arose due to the React-Tooltips library we were using. They had several bugs they did not intend to fix (they didn't want to allow their tooltips to accept JSX, despite React and JSX going hand in hand, simply because JSX was confusing to them... which isn't a valid reason for them to ignore it, in our opinion), so that is why we made the switch to the popovers. By doing this, we could inject the JSX into the popovers and avoid this bug.
