### ISSUE TITLE
Nav bar disappears upon zooming in

### ISSUE THREAD

**Issue by akkarh** [plastic-oceans461/plastic-oceans461.github.io#24]
![image](https://user-images.githubusercontent.com/24836340/40898087-e0aa0e1a-6773-11e8-92bb-35b3fecfe363.png)

Minor bug: navigation bar disappears upon zooming in on the map

**Comment by lisakoss** [comment]
Are you using your trackpad to zoom in? Chrome appears to have this "zooming" feature that you can do with your trackpad and still keep a "100%" zoom on the browser window itself. But, if you scroll up (don't drag up on the map), you'll see that the navigation bar is still present. Since this feature is simply part of Chrome (this doesn't happen in Firefox) and how it works (the same behavior is found on other websites), I don't think I'll classify this as a bug. :)

**Comment by akkarh** [comment]
Yes, I was using the trackpad. I tried out the app again and scrolled up, and the nav bar was present!

**Comment by lisakoss** [comment]
Awesome! :) I'll close this then since this behavior is consistent with all websites visited on Google Chrome.
