### ISSUE TITLE
I cannot get it to open

### ISSUE THREAD

**Issue by harrybarng** [plastic-oceans461/plastic-oceans461.github.io#31]
The website is just blank and cannot get it to open even if I refresh 20 times on chrome and incognito chrome

![image](https://user-images.githubusercontent.com/37923379/40904575-0591c86e-6790-11e8-8a03-ea734d9a3ae5.png)

**Comment by alexiskoss** [comment]
It looks like our professor hasn't updated our link yet on the website. Feel free to check us out here: https://plastic-oceans.herokuapp.com/ We had a few failed deployment attempts earlier and had to redeploy at a different link.

Closing this because I already have it marked as a major bug in another issue. :)
